services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: stratego
      POSTGRES_PASSWORD: ENTER_YOUR_PASSWORD_HERE
      POSTGRES_DB: stratego_app_server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./Environment/db_init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4.1
    restart: always

  adminer:
    image: dockette/adminerevo
    restart: always
    ports:
      - 8080:8080

  server:
    ports:
      - 8123:5000
      - 8124:5001

    build:
      context: .
      dockerfile: Dockerfile-server
      args:
        db_type: Postgres
        db_host: db
        db_port: 5432
        db_name: stratego_app_server
        db_user: stratego
        db_password: ENTER_YOUR_PASSWORD_HERE
        redis_host: redis
        redis_port: 6379 
    depends_on:
      - redis
      - db

  game_node:
    build:
      context: .
      dockerfile: Dockerfile-game-node
      args:
        - redis_url=redis://redis:6379
    depends_on:
      - redis
    
volumes:
  pgdata: 
  f:
